version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - %(message)s"
    complete:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    short:
        format: "%(levelname)s - %(message)s"
    message_only:
        format: "%(message)s"
        
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: message_only
        stream: ext://sys.stdout
                
    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: complete
        filename: debug.log
        maxBytes: 1000000
        backupCount: 1
        encoding: utf8

loggers:
    manuskript:
        level: DEBUG
        handlers: [console, file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
    propagate: yes